### ISSUE TITLE
Falha ao verificar permissões de câmera 

### ISSUE THREAD

**Issue by dsdebastiani** [gcherubini/KamuMobile#6]
Aparentemente o bug está ocorrendo por alguma falha no método:

```ActivityCompat.shouldShowRequestPermissionRationale(this, permission)```

Debugando eu percebi que ele é chamado inumeras vezes até o app crashar.

Pode ser uma falha na lib CoreCompat do AndroidX.

Stack trace:
```
2019-04-04 12:33:33.126 26100-26100/com.thoughtworks.kamu E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.thoughtworks.kamu, PID: 26100
    java.lang.StackOverflowError: stack size 8MB
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
2019-04-04 12:33:33.185 26100-26100/com.thoughtworks.kamu E/AndroidRuntime:     at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
2019-04-04 12:33:41.054 26100-26100/com.thoughtworks.kamu I/chatty: uid=10211(com.thoughtworks.kamu) identical 201 lines
2019-04-04 12:33:41.093 26100-26100/com.thoughtworks.kamu E/AndroidRuntime:     at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
2019-04-04 12:33:41.134 26100-26100/com.thoughtworks.kamu E/AndroidRuntime:     at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
        at com.thoughtworks.kamu.presenter.base.BaseActivity.shouldShowRequestPermissionRationale(BaseActivity.kt:42)
        at com.thoughtworks.kamu.presenter.isbnreader.IsbnReaderViewModel.onResume(IsbnReaderViewModel.kt:34)
        at com.thoughtworks.kamu.presenter.isbnreader.IsbnReaderViewModel_LifecycleAdapter.callMethods(IsbnReaderViewModel_LifecycleAdapter.java:31)
        at androidx.lifecycle.SingleGeneratedAdapterObserver.onStateChanged(SingleGeneratedAdapterObserver.java:35)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:355)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:293)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:333)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:138)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:124)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:122)
        at androidx.lifecycle.ReportFragment.onResume(ReportFragment.java:89)
        at android.app.Fragment.performResume(Fragment.java:2568)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1341)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3046)
        at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3008)
        at android.app.FragmentController.dispatchResume(FragmentController.java:204)
        at android.app.Activity.performResume(Activity.java:7314)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3777)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3817)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
````

**Comment by dsdebastiani** [comment]
Tenho uma hipótese para o problema baseado nessas respostas que encontrei no SatackOverflow:
https://stackoverflow.com/a/39739972

O erro pode estar ocorrendo pois estamos fazendo a verificação sem nunca ter solicitado alguma permissão antes.

Segundo essa outra resposta, podemos montar um fluxo de permissões:
https://stackoverflow.com/a/37851808

Ainda assim, acredito ser um bug no AndroidX CompatActivity. Se for o caso podemos abrir uma issue aqui: https://issuetracker.google.com/issues?q=status:open%20shouldShowRequestPermissionRationale

**Comment by gcherubini** [comment]
1. O erro pode estar ocorrendo pois estamos fazendo a verificação sem nunca ter solicitado alguma permissão antes.

Este não é o problema, fiz um teste sempre requisitando a permissão antes de realizar a verificação "shouldShowRequestPermissionRationale"

**Comment by dsdebastiani** [comment]
PR  #7 corrige o problema.

Só para deixar como registro. Nossa `BaseActivity` implementa a interface `PermissableActivity` que coincidentemente possuía o método `shouldShowRequestPermissionRationale` com o mesmo nome do método existente na própria `Activity` e `AppCompatActivity`. Devido a anotação `override` no método, ficava ambíguo a implementação  do método, causando uma chamada recursiva.

```
    override fun shouldShowRequestPermissionRationale(permission: String): Boolean {
        return ActivityCompat.shouldShowRequestPermissionRationale(this, permission)
    }
```
